title = "Composable CDP with Predictive ML Modeling"
baseURL = "https://docs.snowplow.io/accelerators/composable-cdp-with-predictive-ml-modeling/"

[params]
  description = "Tutorial building a composable CDP with predictive ML modeling using Snowplow, Databricks and Hightouch"
  author = "Snowplow, George Woodhead"
